version: '3.8'

services:
  app:
    image: node:16.13.2-slim
    working_dir: /app
    volumes:
      - ./app:/app
    ports:
      - 3000:3000
    command:  bash -c "npm i && npm run dev"

  api:
    build: ./api
    volumes:
      - ./api:/api
    ports:
      - 8000:8000
